[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/auth/discord/login"
  to = "/.netlify/functions/discord-login"
  status = 200

[[redirects]]
  from = "/auth/discord/callback"
  to = "/.netlify/functions/discord-callback"
  status = 200

[[redirects]]
  from = "/auth/me"
  to = "/.netlify/functions/auth-me"
  status = 200

[[redirects]]
  from = "/auth/logout"
  to = "/.netlify/functions/auth-logout"
  status = 200
